/* 

1. blog section will sliding ...
2. testimonials will sliding ...
3. remove img from contact sec ...
6. vision mission card in the home page ...
5.add pricing after services ...
7. the content in the services card will be limited and the size will be same, color will be same - heading (services) 
4.change ex team content form c gpt

*/